[package]
name = "ai_sdk"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }


[dev-dependencies]
tokio = { workspace = true }
