services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DATABASE: chat
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_HOST: 0.0.0.0

volumes:
  clickhouse:
