services:
  # The postgres database.
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-pgvector.sh:/docker-entrypoint-initdb.d/init-pgvector.sh
    ports:
      - "5432:5432"
volumes:
  pgdata:
