#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CLICKHOUSE_DATABASE
              value: chat
            - name: CLICKHOUSE_USER
              value: clickhouse
            - name: CLICKHOUSE_PASSWORD
              value: clickhouse
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: chat-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-essd
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: chat-app
spec:
  selector:
    app: clickhouse
  ports:
    - name: http
      protocol: TCP
      port: 8123
