server:
  port: 8080
  host: 0.0.0.0
  db_url: postgresql://postgres:pnnnfd86@dbprovider.us-east-1.clawcloudrun.com:37389/chat
  base_dir: /Users/kevin.yang/Downloads/chat_server
auth:
  sk: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIA4mh6ctXYftfwRb4je+XyO+D47YNI6ytsmAPpQFq+rt
    -----END PRIVATE KEY-----
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAXb0Hfuxwr6GN5eMHesm5LmYGATOArNiN7JYQOiDhVag=
    -----END PUBLIC KEY-----
